## INTRASTAT COMMODITY CODES CHECK

Overview: Intrastat is a system that collects information relating to the trade of goods. This script will make a call to the UK Trade Tariff Public API, to check the commodity code under test. 

Task:

Below outlines the steps to be performed:

1) Import the necessary libraries for the project.
2) Define the functions that will faciliate the commodity check.
3) Send request to API and test for succesful response. 
4) Parse the api response content into a pandas dataframe.
5) Verify script with test data.

In [96]:
import requests
import json
import pandas as pd

API_URL = 'https://ec.europa.eu/taxation_customs/vies/rest-api/ms/'
COLUMNS_RESP = ["Vat Number","Response Code", "Valid", "Company", "Address","Request Date"]

def request(vat):
    # Send API request.
    vat_no = vat[2::]
    alpha2 = vat[:2:]
    response_API = requests.get(API_URL + alpha2 + '/vat/' + vat_no)
    data = json.loads(response_API.text)
    data = [data['vatNumber'],response_API.status_code,data['isValid'],
             data['name'],data['address'], data['requestDate'][:10:]]
    # Store response results in list. 
    return data

def run_check(df, column_name):
    # Run validity check on each row of dataframe. Append response. 
    data = [request(v) for v in df[column_name]]
    df_out = pd.DataFrame(data,columns=COLUMNS_RESP)
    df_out = pd.merge(df, df_out, left_index=True, right_index=True)
    return df_out

def main():
    data = ['ATU25700701','NL003903175B01','SK2020229618','FI15601431','PL52200000XX']
    df = pd.DataFrame(data,columns=['VAT']) 
    display(run_check(df,'VAT'))
        
if __name__ == '__main__':
    main()

,VAT,Vat Number,Response Code,Valid,Company,Address,Request Date
0,ATU25700701,U25700701,200,True,adidas Austria GmbH,Adi-Dassler-Gasse 6\nAT-9073 Klagenfurt am Wör...,2023-07-23
1,NL003903175B01,003903175B01,200,True,ADIDAS BENELUX B.V.,\nHOOGOORDDREEF 00009 A\n1101BA AMSTERDAM\n,2023-07-23
2,SK2020229618,2020229618,200,True,"adidas Slovakia, s.r.o.","Prievozská 4D, Blok\n82109 Bratislava - mestsk...",2023-07-23
3,FI15601431,15601431,200,True,Adidas Suomi Oy,c/oadidas Factory Outlet Valimokuja 2\n01510 V...,2023-07-23
4,PL52200000XX,52200000XX,200,False,---,---,2023-07-23