In [15]:
import pandas as pd
import re 

df_data = pd.read_csv("MarketRevenueAnnual(C).csv")
df_thresh = pd.read_csv("ThresholdsVAT.csv")
df = pd.merge(df_data, df_thresh, on="Country")
df = df.drop(columns = 'ISO')

def df_columns_to_sum_only(df):
    columns =  [x for x in df.columns if re.match("^\d{4}",x)]
    df = df[columns]
    return df

def breach_cond(turnover, threshold):
    if turnover<threshold:
        return False
    else: return True

def breach_calc(df,country):
    df = df.loc[df['Country'] == country]
    df_turnover = df_columns_to_sum_only(df).astype(int)
    run_total = 0
    threshold = df['Threshold'].astype(int).iloc[0]
    for i in range(len(df_turnover.columns)-1):
        year = df_turnover.columns[i]
        turnover = run_total + df_turnover[year].iloc[0]
        if breach_cond(turnover,threshold):
            return year
            break
        else: run_total = turnover
    return 'No Breach'

df['Breach'] = [breach_calc(df,x) for x in df['Country']]

display(df)

       Country  2020  2021  2022  2023  2024  Threshold     Breach
0      Belgium  2254  3350  6143  8493  1022      25000  No Breach
1       France  3822  5949  7489  8330  1830       3400       2020
2      Germany  3777  6830  8483  7373  1309       2200       2020
3  Netherlands  2818  3847  6859  7732  1258       2500       2020
4        Spain  2498  4933  5849  6820  1446       1000       2020